from __future__ import annotations

import argparse
import json
import re
import urllib.request
from pathlib import Path
from typing import Any

IMAGE_FIELDS = [
    "icon_image_small",
    "icon_hero_card",
    "minimap_image",
    "name_image",
    "top_bar_vertical_image",
    "background_image",
    "hero_card_critical",
    "hero_card_gloat",
    "weapon_image",
]

PANORAMA_RE = re.compile(r'^panorama:"file://\{images\}/(.+)"$')


def parse_panorama_asset(value: Any) -> str | None:
    if not isinstance(value, str):
        return None
    match = PANORAMA_RE.match(value)
    if not match:
        return None
    return match.group(1)


def normalize_web_path(asset_path: str | None) -> str | None:
    if not asset_path:
        return None

    if asset_path.lower().endswith(".svg"):
        return f"/assets/{asset_path}"

    if asset_path.lower().endswith(".psd"):
        return f"/assets/{asset_path[:-4]}.png"

    return f"/assets/{asset_path}"


def to_download_relative(asset_path: str | None) -> str | None:
    if not asset_path:
        return None

    if asset_path.lower().endswith(".psd"):
        return asset_path[:-4] + ".png"

    return asset_path


def build_hero_assets(parsed: list[dict[str, Any]]) -> list[dict[str, Any]]:
    heroes: list[dict[str, Any]] = []

    for hero in parsed:
        try:
            hero_id = int(hero.get("id"))
        except (TypeError, ValueError):
            continue

        icon_fields: dict[str, dict[str, Any]] = {}

        for field in IMAGE_FIELDS:
            raw_value = hero.get(field)
            asset_path = parse_panorama_asset(raw_value)
            icon_fields[field] = {
                "raw": raw_value,
                "assetPath": asset_path,
                "webPath": normalize_web_path(asset_path),
            }

        heroes.append(
            {
                "id": hero_id,
                "className": hero.get("class_name"),
                "heroType": hero.get("hero_type"),
                "iconFields": icon_fields,
            }
        )

    heroes.sort(key=lambda h: h["id"])
    return heroes


def write_json_output(output_file: Path, heroes: list[dict[str, Any]]) -> None:
    payload = {
        "generatedAt": __import__("datetime").datetime.utcnow().isoformat() + "Z",
        "heroCount": len(heroes),
        "heroes": heroes,
    }
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def write_ts_output(output_file: Path, heroes: list[dict[str, Any]], source_file: Path) -> None:
    source = source_file.as_posix()
    generated_at = __import__("datetime").datetime.utcnow().isoformat() + "Z"

    ts = f'''/* eslint-disable */
// Auto-generated by scripts/extract_hero_assets.py
// Source: {source}
// Generated at: {generated_at}

export type HeroImageField = {{
  raw: string | null;
  assetPath: string | null;
  webPath: string | null;
}};

export type HeroAssetEntry = {{
  id: number;
  className: string | null;
  heroType: string | null;
  iconFields: Record<string, HeroImageField>;
}};

export const HERO_ASSETS: HeroAssetEntry[] = {json.dumps(heroes, indent=2)};

export const HERO_ASSETS_BY_ID: Record<number, HeroAssetEntry> = Object.fromEntries(
  HERO_ASSETS.map((entry) => [entry.id, entry])
) as Record<number, HeroAssetEntry>;
'''

    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(ts, encoding="utf-8")


def download_images(
    heroes: list[dict[str, Any]],
    download_base_url: str,
    public_assets_dir: Path,
    timeout_s: int,
) -> tuple[int, int]:
    base = download_base_url.rstrip("/")
    downloaded = 0
    failed = 0
    seen: set[str] = set()

    for hero in heroes:
        icon_fields = hero.get("iconFields", {})
        for field in IMAGE_FIELDS:
            field_data = icon_fields.get(field, {})
            relative = to_download_relative(field_data.get("assetPath"))
            if not relative or relative in seen:
                continue

            seen.add(relative)
            target = public_assets_dir / relative
            target.parent.mkdir(parents=True, exist_ok=True)

            url = f"{base}/{relative}"
            try:
                with urllib.request.urlopen(url, timeout=timeout_s) as response:
                    content = response.read()
                target.write_bytes(content)
                downloaded += 1
            except Exception:
                failed += 1

    return downloaded, failed


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract hero icon/image metadata from hero_data.json and optionally download images."
    )
    parser.add_argument("input", help="Path to hero_data.json")
    parser.add_argument(
        "--json-output",
        default="lib/heroAssets.generated.json",
        help="Output JSON metadata path (default: lib/heroAssets.generated.json)",
    )
    parser.add_argument(
        "--ts-output",
        default="lib/heroAssets.generated.ts",
        help="Output TS metadata path (default: lib/heroAssets.generated.ts)",
    )
    parser.add_argument(
        "--download-base-url",
        default=None,
        help="Optional CDN/base URL to download images from (relative asset paths are appended).",
    )
    parser.add_argument(
        "--public-assets-dir",
        default="public/assets",
        help="Where downloaded images are written (default: public/assets)",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=15,
        help="Download timeout in seconds (default: 15)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    input_file = Path(args.input).expanduser().resolve()
    if not input_file.exists():
        raise SystemExit(f"Input file not found: {input_file}")

    raw = input_file.read_text(encoding="utf-8")
    parsed = json.loads(raw)

    if not isinstance(parsed, list):
        raise SystemExit("Expected hero_data JSON to be an array.")

    heroes = build_hero_assets(parsed)

    json_output = Path(args.json_output).expanduser().resolve()
    ts_output = Path(args.ts_output).expanduser().resolve()

    write_json_output(json_output, heroes)
    write_ts_output(ts_output, heroes, input_file)

    print(f"Wrote {len(heroes)} heroes to {json_output}")
    print(f"Wrote {len(heroes)} heroes to {ts_output}")

    if args.download_base_url:
        public_assets_dir = Path(args.public_assets_dir).expanduser().resolve()
        downloaded, failed = download_images(
            heroes=heroes,
            download_base_url=args.download_base_url,
            public_assets_dir=public_assets_dir,
            timeout_s=args.timeout,
        )
        print(f"Downloaded images: {downloaded}")
        print(f"Failed downloads: {failed}")
        print(f"Image output dir: {public_assets_dir}")


if __name__ == "__main__":
    main()
